baseURL = "http://www.example.com"
title = "Xiaoteng Ma"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Xiaoteng Ma"
description = "Xiaoteng's personal website"
keywords = "homepage,personal"
#info = ["ma-xt17[AT]mails[DOT]tsinghua[DOT]edu[DOT]cn"]
info = ["Make the machine a friend of human,", "More humanistic, reliable, and efficient."]
avatarURL = "images/avatar_xiaoteng.jpg"
favicon_16 = "images/icons8-horse-stable-16.png"
favicon_32 = "images/icons8-horse-stable-32.png"
touchIcon = "images/icons8-horse-stable-100.png"
katex = "true"
# math = true
#gravatar = "john.doe@example.com"
footerContent = "Where my heart lies, let my brain lie also."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/xtma/"

[[params.social]]
name = "Google Scholar"
icon = "fa fa-google"
weight = 2
url = "https://scholar.google.com/citations?user=CeDFnNMAAAAJ"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Publication"
weight = 2
url = "publication/"

# [languages.cn]
# languageName = ":brazil:"
# title = "João Ninguém"
# 
# [languages.cn.params]
# author = "João Ninguém"
# info = "Full Stack DevOps e Mágico"
# description = "Sítio pessoal de João Ninguém"
# keywords = "blog,desenvolvedor,pessoal"
# footerContent = "Coloque algum texto aqui."
# 
# [[languages.cn.menu.main]]
# name = "Sobre"
# weight = 1
# url = "about/"
# 
# [[languages.cn.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"
# 
# [[languages.cn.menu.main]]
# name = "Projetos"
# weight = 3
# url = "projects/"
# 
# [[languages.cn.menu.main]]
# name = "Contato"
# weight = 5
# url = "contact/"
